# Generated by Django 4.1.1 on 2022-09-26 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("unity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255)),
                ("status", models.IntegerField(default=1)),
                ("is_email_sent", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_visitor_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "visitor_emails",
                "ordering": ("-pk",),
            },
        ),
        migrations.DeleteModel(
            name="Email",
        ),
    ]
