# Generated by Django 4.1.1 on 2022-09-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("unity", "0004_seller_visitoremail_seller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
