# Generated by Django 4.1.1 on 2022-09-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unity", "0005_remove_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitoremail",
            name="is_email_sent",
        ),
        migrations.AddField(
            model_name="seller",
            name="is_email_sent",
            field=models.IntegerField(default=1),
        ),
    ]
